apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password: redhat
  
resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  

# kubectl create -k .
