apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs1
  
spec:
  replicas: 2
  selector:
      matchLabels:
        app: web
      matchExpressions:
      - { key: dc, operator: In, values: [south] }
      - { key: region, operator: In, values: [IN] }
  
  template:
    metadata:
        name: "mypod"
        labels: 
          dc: south
          region: IN
          app: web
    spec: 
        containers:
        - name: "myc1"
          image: "vimal13/apache-webserver-php"
