apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs1
  
spec:
  replicas: 2
  selector:
      matchLabels:
        app: web
      matchExpressions:
      - { key: dc, operator: In, values: [south] }
      - { key: region, operator: In, values: [IN] }
