apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: managed-nfs-storage

provisioner: k8s-sighs.io/nfs-subdir-external-provisioner
parameters: 
    pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
    onDelete: delete
